### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by bradleyayers** [dnut/Rewrap#6]
When using the release version I get the following error when trying to wrap a comment:

```
[Extension Host] TypeError: Cannot read properties of undefined (reading 'value')
    at $5dda3e6a28d5613b$var$getWrappingColumns (/Users/brad/.vscode/extensions/dnut.rewrap-revived-1.16.3/dist/Extension.js:12731:15)
    at $5dda3e6a28d5613b$export$55f23a6172c4a901 (/Users/brad/.vscode/extensions/dnut.rewrap-revived-1.16.3/dist/Extension.js:12714:18)
    at $5dda3e6a28d5613b$export$7b76d8f1f719850 (/Users/brad/.vscode/extensions/dnut.rewrap-revived-1.16.3/dist/Extension.js:12698:22)
    at $d750fd4ee536bd19$var$doWrap (/Users/brad/.vscode/extensions/dnut.rewrap-revived-1.16.3/dist/Extension.js:12964:69)
    at rewrapCommentCommand (/Users/brad/.vscode/extensions/dnut.rewrap-revived-1.16.3/dist/Extension.js:12929:9)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:36980
    at Object.edit (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:7093)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:36968
    at cw.h (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32833)
    at cw.$executeContributedCommand (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:33683)
    at Dy.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
    at Dy.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
    at Dy.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
    at Dy.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113249)
    at kh.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at kh.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

The language is TypeScript.

**Comment by dnut** [comment]
This is on the stable release 1.16.3? Are you able to reproduce this error in any way, or it only happened that one time?

**Comment by bradleyayers** [comment]
> This is on the stable release 1.16.3? Are you able to reproduce this error in any way, or it only happened that one time?

Just the one time, I haven't run into it again.

**Comment by matthiasgeihs** [comment]
A couple of these have been reported previously:
https://github.com/stkb/Rewrap/issues/311
https://github.com/stkb/Rewrap/issues/326

**Comment by dnut** [comment]
@matthiasgeihs have you observed this same problem?

Looks like this is generally difficult to reproduce, but the original author believed that the pre-release version would resolve this issue.

Hopefully, people are testing out the pre-release version, as I've recommended. I haven't seen any reports come in for issues with the pre-release version. So, I will likely upgrade the stable release version soon.
